# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=100)),
                ('band_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('create_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('hometown', models.CharField(max_length=150)),
                ('twitter_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.CharField(max_length=100)),
                ('band_name', models.CharField(max_length=150, unique=True)),
                ('genre_id', models.CharField(max_length=150)),
                ('year_span', models.IntegerField()),
                ('hometown', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('twitter_id', models.CharField(max_length=150)),
            ],
        ),
    ]
